### ISSUE TITLE
How i can test the event invoke?

### ISSUE THREAD

**Issue by khanghoang** [jesstelford/react-testing-mocha-jsdom#2]
Hi there.
I just changed from Jest to Mocha because of Jest is so slow when running tests. But i have a question, let say i wanna test the onClick of the component is invoked, how can i do it?

**Comment by jesstelford** [comment]
You can add the following test to `test/component/todo-item.js`:

```javascript
  it('clicking <input> should check it', function() {
    this.inputElement.click();
    assert(this.inputElement.checked === true);
  });
```

If you want to test the code that the onClick handler actually executes, then you should extract it out into a testable module that doesn't require react at all to be tested.

Essentially, you should mostly avoid testing if react is "working" - that is the responsibility of the framework's tests. Your tests should only be for side-effects (events being fired, DOM updated, etc).
