### ISSUE TITLE
how to test my react components that importing stylesheet file ?

### ISSUE THREAD

**Issue by zernmal** [jesstelford/react-testing-mocha-jsdom#9]
I’v import the .less file in my component and build the script whit webpack , link this:
``` javascript
require('index.less');
var React = require('react');
// and more code
```
now , if I use the unit test whit mocha and jsdom , it will throw the syntax error when the test program run the less file, what can I do?

**Comment by nicomfe** [comment]
I came across this a while ago and I found 2 ways of fixing it:

FIRST OPTION) Include library [ignore-styles ](https://www.npmjs.com/package/ignore-styles)
And then run mocha --require ignore-styles <your test file/s>

_i.e: mocha --require ignore-styles __test__/my-test-file.js_

SECOND OPTION) Create your custom pre processor file with this content:

```
// Prevent Mocha from compiling resources like css, scss or svg
function noop() {
  return null;
}
require.extensions['.css'] = noop;
require.extensions['.scss'] = noop;
require.extensions['.svg'] = noop;
```

This last option is useful if you have not only css resources but others like svg, png, etc.

And then you run mocha --require [path to your preprocessor] [your test files]
_i.e: mocha --require my-preprocessor.js __test__/my-test-file.js_

**Comment by zernmal** [comment]
it work, Thx
